language: java
install: true

dist: trusty
jdk: openjdk8

before_install:
  - wget https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
  - unzip -qq gradle-5.6.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
script:
#  - gradle clean build --scan -s --debug
  - gradle clean build --scan -s
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
